main: jibsplugin.ofstuff.Main
name: JibsPluginOfStuff
version: 1.0
author: DoomeDxx and JibblyJ
description: Freedom United's one plugin to rule them all!
commands:
  clearchat:
    description: Clears the chat
    usage: /clearchat
    permission: jibspluginofstuff.clearchat
    permission-message: §cYou don't have permission to use that command.
